#!/bin/bash


typeset -i toronto=6167863
typeset -i ottawa=6094817

latitude=`whereami -r | sed 's/[^[:print:]]//g' | tail -14 | sed 's/\[1000D\[K\[1A\[1000D\[K//' | sed 's/\[?25h//' | jq '.latitude'` 
longitude=`whereami -r | sed 's/[^[:print:]]//g' | tail -14 | sed 's/\[1000D\[K\[1A\[1000D\[K//' | sed 's/\[?25h//' | jq '.longitude'`
city=`whereami -r | sed 's/[^[:print:]]//g' | tail -14 | sed 's/\[1000D\[K\[1A\[1000D\[K//' | sed 's/\[?25h//' | jq '.city'`

echo ================================================
echo ++ `date | cut -c -15` ++

echo your longitude: $longitude
echo your latitude: $latitude
url=("curl --silent -o /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data -X GET 'https://api.openweathermap.org/data/2.5/weather?lat=$latitude&lon=$longitude&units=metric&APPID=6bfa2458671bc7e9c25c43b61b7d71b3'")
eval $url

echo +----------------------------------------------+
echo Your current weather forecast in $city:
echo "It is `cat /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data | jq '.main.temp'`C "
echo "And it feels like `cat /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data | jq '.main.feels_like'`C "
echo "The weather is `cat /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data | jq '.weather[0].description'` "
echo "+=---------------------=+"
echo "Max today: `cat /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data | jq '.main.temp_max'`C"
echo "Min today: `cat /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data | jq '.main.temp_min'`C"
echo "Humidity: `cat /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data | jq '.main.humidity'` percent "

echo +----------------------------------------------+
Sunrise=`cat /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data | jq '.sys.sunrise'`
Sunset=`cat /home/$USER/Documents/git_repos/Weather/bash-weather/JSON_data | jq '.sys.sunset'`
echo Sunrise: `date -d@$Sunrise | cut -c 17-`
echo Sunset: `date -d@$Sunset | cut -c 17-`

echo ================================================

